
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Carrie Wright](https://carriewright11.github.io/) and [Stephanie Hicks](https://www.stephaniehicks.com/)|
|Lecturer(s) | [Michael Breshock](https://mbreshock.github.io/) and [Qier Meng](https://www.linkedin.com/in/qier-meng-41769a194/)|
|Content Author(s) | [Michael Breshock](https://mbreshock.github.io/) and [Lyla Atta](https://lylaatta.github.io/) and [Carrie Wright](https://carriewright11.github.io/)|
|Content Director(s) | [Carrie Wright](https://carriewright11.github.io/) and [Stephanie Hicks](https://www.stephaniehicks.com/)|
|Acknowledgments| [Shannon Ellis](https://www.shanellis.com/), [Jeff Leek](https://jtleek.com/), and [Roger Peng](https://rdpeng.org/) - Thank you for your resources on your uses of case studies from OCS!|
|**Production**||
|Content Publisher(s)| Helped with publishing platform|
|Content Publishing Reviewer(s)| Reviewed overall content and aesthetics on publishing platform|
|**Technical**||
|Course Publishing Engineer(s)| [Carrie Wright], [Candace Savonen]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottr])|[John Muschelli], [Candace Savonen], [Carrie Wright]|
|**Art and Design**||
|Illustrator(s)|[Lyla Atta], [Carrie Wright]|
|Videographer(s)| [Michael Breshock](https://mbreshock.github.io/) and [Qier Meng](https://www.linkedin.com/in/qier-meng-41769a194/)|
|Videography Editor(s)| [Michael Breshock](https://mbreshock.github.io/) and [Lyla Atta](https://lylaatta.github.io/)|
|**Funding**||
|Funder(s)| This guide was funded as an extension to funding for the [Genomic Data Science Community Network (GDSCN)](https://arxiv.org/abs/2201.08443). The GDSCN is supported through a contract to Johns Hopkins University (75N92020P00235) NHGRI.|
|Funding Staff| [Jennifer Vessio](https://www.linkedin.com/in/jennifer-vessio-0a240888/)|

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[FirstName LastName]: link to personal website
[John Muschelli]: https://johnmuschelli.com/
[Candace Savonen]: https://www.cansavvy.com/
[Carrie Wright]: https://carriewright11.github.io/
[Michael Breshock]: https://mbreshock.github.io/
[Stephanie Hicks]

<!-- Links -->

[ottr]: https://github.com/jhudsl/ottr

<!-- Fill out this table using these instructions: https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits

For JHU courses, You will need to add Ira as a credit:

|Content Publisher|[Ira Gooding]|
...
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
-->
